import type { Product, Artisan, Collection, SiteConfig } from "./types";

export const seedCollections: Collection[] = [
  {
    id: "home-decor",
    name: "Home Decor",
    slug: "home-decor",
    description: "Transform your living space with handcrafted crochet art",
    coverImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&h=600&q=80",
    featured: true,
    active: true,
    order: 1,
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Carry handmade art wherever you go",
    coverImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&h=600&q=80",
    featured: true,
    active: true,
    order: 2,
  },
  {
    id: "jewelry",
    name: "Jewelry",
    slug: "jewelry",
    description: "Delicate crochet jewelry with timeless soul",
    coverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&h=600&q=80",
    featured: true,
    active: true,
    order: 3,
  },
  {
    id: "gifting",
    name: "Gifting",
    slug: "gifting",
    description: "Thoughtful, handmade gifts that tell a story",
    coverImage: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&h=600&q=80",
    featured: true,
    active: true,
    order: 4,
  },
];

export const seedArtisans: Artisan[] = [
  {
    id: "asha-devi",
    name: "Asha Devi",
    village: "Sanganer",
    state: "Rajasthan",
    bio: "Asha Devi weaves stories of Rajasthan's desert blooms into every piece she creates. Her wall hangings and home decor have found homes across India and beyond.",
    shortBio: "Master of wall hangings and home décor inspired by Rajasthan's desert blooms.",
    photo: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&w=600&h=800&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1616627452249-3adf9f4f0db2?auto=format&fit=crop&w=800&q=80",
    ],
    story: `Asha Devi grew up watching her mother crochet in the early morning light of their Sanganer home. At twelve, she learned her first stitch — a chain that would eventually link her to a global community of craft lovers.\n\nFor over a decade she sold her work at local haats for less than the cost of her yarn. When she joined the Trendy Threadz collective in 2021, everything changed. Her pieces now sell at fair prices, her children are in school, and she trains twelve other women in her village.\n\n"I never imagined someone in another country would hang my work on their wall," she says, a smile spreading across her face. "Every stitch I make now, I make with that person in my heart."`,
    craft: "Home Decor & Wall Hangings",
    yearsOfExperience: 12,
    productsMade: 340,
    familySize: 5,
    featured: true,
    active: true,
    createdAt: "2021-06-15T10:00:00Z",
  },
  {
    id: "meera-kumari",
    name: "Meera Kumari",
    village: "Bhuj",
    state: "Gujarat",
    bio: "From the salt flats of Kutch, Meera brings the geometric patterns of Rann embroidery into her crochet bags and accessories.",
    shortBio: "Kutch artisan blending geometric Rann patterns into wearable art.",
    photo: "https://images.unsplash.com/photo-1610021684276-dce882f14f3e?auto=format&fit=crop&w=600&h=800&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    ],
    story: `Meera Kumari's hands have never been still. Growing up in the artisan district of Bhuj, she absorbed Kutch's legendary textile traditions through osmosis — watching, asking, and eventually creating.\n\nHer crochet bags carry the bold geometry of Rann embroidery, reimagined in cotton yarn that travels light. Each piece takes three to five days, with patterns that emerge from memory rather than a pattern book.\n\nSince joining Trendy Threadz, Meera has trained eight women in her neighbourhood and saved enough to renovate her family home. "My craft is my income, my identity, and my joy," she says. "Now it is all three."`,
    craft: "Bags & Accessories",
    yearsOfExperience: 8,
    productsMade: 212,
    familySize: 4,
    featured: true,
    active: true,
    createdAt: "2021-09-01T10:00:00Z",
  },
  {
    id: "kavita-ben",
    name: "Kavita Ben",
    village: "Nashik",
    state: "Maharashtra",
    bio: "A self-taught jewellery maker from Maharashtra, Kavita transforms fine cotton thread into heirloom-quality pieces inspired by local flora.",
    shortBio: "Self-taught jeweller turning fine cotton thread into floral heirlooms.",
    photo: "https://images.unsplash.com/photo-1573497019236-17f8177b81e8?auto=format&fit=crop&w=600&h=800&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    ],
    story: `Kavita Ben discovered crochet jewellery through a YouTube tutorial in 2014 and spent two years teaching herself from videos before selling her first piece. Today she is the undisputed master of crochet jewellery in her district.\n\nEach of her pieces begins with a sketch inspired by the wildflowers around Nashik — lotus, marigold, jasmine. She works with the finest mercerised cotton, building intricate structures one tiny stitch at a time.\n\nShe sells through Trendy Threadz, teaches workshops on weekends, and is saving to open a small studio where other women can learn. "I started with nothing but a YouTube video," she laughs. "Now I teach."`,
    craft: "Jewelry & Wearables",
    yearsOfExperience: 10,
    productsMade: 480,
    familySize: 3,
    featured: true,
    active: true,
    createdAt: "2021-04-20T10:00:00Z",
  },
  {
    id: "parvati-bai",
    name: "Parvati Bai",
    village: "Lucknow",
    state: "Uttar Pradesh",
    bio: "With 15 years of experience, Parvati brings the elegance of Lucknowi craft traditions into her gift sets and keepsakes.",
    shortBio: "Lucknow's finest, weaving chikan-inspired patterns into crochet gift sets.",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&h=800&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80",
    ],
    story: `Parvati Bai comes from a long line of Lucknowi craftswomen. Her mother did chikankari embroidery; her grandmother did zardozi. Parvati found her medium in crochet — a craft she could do after dark when the children were asleep.\n\nHer gift sets are famous for their delicacy: keychains, coasters, and small ornaments that carry the white-on-white restraint of chikan in yarn form. Buyers say unwrapping one of her hampers feels like opening a treasure box.\n\nShe is the most experienced artisan in the collective and informally mentors the newer members. "When I was young, no one paid fairly for this work," she says. "I am glad that is changing."`,
    craft: "Gifting & Keepsakes",
    yearsOfExperience: 15,
    productsMade: 620,
    familySize: 6,
    featured: false,
    active: true,
    createdAt: "2020-11-10T10:00:00Z",
  },
];

export const seedProducts: Product[] = [
  {
    id: "sunflower-planter",
    name: "Sunflower Planter Holder",
    slug: "sunflower-planter",
    price: 849,
    comparePrice: 1099,
    category: "Home Decor",
    collectionId: "home-decor",
    description: "Hand-crocheted in warm ochre and white cotton, this planter holder cradles your favourite pot in a bloom of sunflower petals. Made by Asha Devi in Sanganer, Rajasthan.",
    details: [
      "100% natural cotton yarn, eco-friendly dyes",
      "Fits pots 4–6 inches in diameter",
      "Hangs from a single hook — hardware included",
      "Wipe clean with damp cloth",
      "Each piece is unique — slight variations are part of its beauty",
    ],
    images: [
      "https://images.unsplash.com/photo-1585038509694-b0b5aa4dda8d?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "asha-devi",
    stock: 14,
    lowStockThreshold: 5,
    featured: true,
    active: true,
    tags: ["home-decor", "planter", "hanging", "cotton"],
    weight: 120,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "mandala-wall-hanging",
    name: "Desert Mandala Wall Hanging",
    slug: "mandala-wall-hanging",
    price: 1499,
    category: "Home Decor",
    collectionId: "home-decor",
    description: "A large circular mandala wall hanging in terracotta, cream, and sage — an ode to Rajasthan's timeless geometry. Statement piece for any wall.",
    details: [
      "60 cm diameter, hangs on a driftwood dowel",
      "Hand-dyed cotton cord, natural driftwood included",
      "Ready to hang out of the box",
      "Spot clean only",
      "Ships rolled to prevent creasing",
    ],
    images: [
      "https://images.unsplash.com/photo-1617396900799-f4ec2b43c7d3?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "asha-devi",
    stock: 6,
    lowStockThreshold: 5,
    featured: true,
    active: true,
    tags: ["home-decor", "wall-hanging", "mandala", "statement"],
    weight: 350,
    createdAt: "2024-01-12T00:00:00Z",
    updatedAt: "2024-01-12T00:00:00Z",
  },
  {
    id: "boho-clutch",
    name: "Boho Crochet Clutch",
    slug: "boho-clutch",
    price: 1199,
    comparePrice: 1499,
    category: "Accessories",
    collectionId: "accessories",
    description: "An elegant hand-stitched clutch with cotton lining, a magnetic clasp, and Kutch-inspired geometric patterns. Big enough for your essentials, beautiful enough to be the look.",
    details: [
      "22 × 14 cm, cotton lining, magnetic clasp",
      "Carry strap included",
      "Fits phone, cards, keys, and lipstick",
      "Spot clean; do not machine wash",
      "Available in natural, terracotta, and ocean blue",
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "meera-kumari",
    stock: 9,
    lowStockThreshold: 5,
    featured: true,
    active: true,
    tags: ["accessories", "clutch", "bag", "boho"],
    weight: 180,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "summer-tote",
    name: "Summer Market Tote",
    slug: "summer-tote",
    price: 1299,
    category: "Accessories",
    collectionId: "accessories",
    description: "Roomy, sturdy, and effortlessly chic. This open-weave tote handles a day at the market or a trip to the beach with equal grace.",
    details: [
      "38 × 40 cm open-weave cotton",
      "Double handles, 28 cm drop",
      "Holds up to 5 kg",
      "Machine washable — cold water, gentle cycle",
      "Colourfast, eco-dyed yarn",
    ],
    images: [
      "https://images.unsplash.com/photo-1573497019236-17f8177b81e8?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "meera-kumari",
    stock: 11,
    lowStockThreshold: 5,
    featured: false,
    active: true,
    tags: ["accessories", "tote", "bag", "market"],
    weight: 260,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "lotus-earrings",
    name: "Lotus Thread Earrings",
    slug: "lotus-earrings",
    price: 549,
    category: "Jewelry",
    collectionId: "jewelry",
    description: "Featherlight crochet earrings shaped like open lotus blooms — in white and gold thread on sterling silver hooks. Goes from day to evening with ease.",
    details: [
      "Sterling silver hooks, hypoallergenic",
      "5 cm drop, 3 cm bloom width",
      "Mercerised cotton thread with gold accent",
      "Presented in a kraft gift box",
      "Available in white/gold, blush/silver, and teal/gold",
    ],
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "kavita-ben",
    stock: 22,
    lowStockThreshold: 5,
    featured: true,
    active: true,
    tags: ["jewelry", "earrings", "lotus", "silver"],
    weight: 8,
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "peacock-necklace",
    name: "Peacock Thread Necklace",
    slug: "peacock-necklace",
    price: 699,
    comparePrice: 899,
    category: "Jewelry",
    collectionId: "jewelry",
    description: "An intricate peacock motif necklace in teal and gold thread, inspired by the national bird of India. A wearable miniature of Indian artistry.",
    details: [
      "45 cm chain with 5 cm extender",
      "Peacock pendant 6 × 4 cm",
      "Teal and gold mercerised cotton",
      "Gold-plated brass chain, nickel-free",
      "Kraft gift box with artisan card",
    ],
    images: [
      "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "kavita-ben",
    stock: 3,
    lowStockThreshold: 5,
    featured: false,
    active: true,
    tags: ["jewelry", "necklace", "peacock", "statement"],
    weight: 22,
    createdAt: "2024-02-05T00:00:00Z",
    updatedAt: "2024-02-05T00:00:00Z",
  },
  {
    id: "heritage-keychain",
    name: "Heritage Keychain Set",
    slug: "heritage-keychain",
    price: 349,
    category: "Gifting",
    collectionId: "gifting",
    description: "A set of three colourful crochet keychains — elephant, lotus, and peacock motifs — made with eco-friendly dyed yarn. Perfect for gifting to someone who loves India.",
    details: [
      "Set of 3 keychains, each ~8 cm",
      "Solid brass rings",
      "Eco-friendly, non-toxic dyes",
      "Presented on a branded gift card",
      "Motifs: elephant, lotus, peacock",
    ],
    images: [
      "https://images.unsplash.com/photo-1616627452249-3adf9f4f0db2?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "parvati-bai",
    stock: 30,
    lowStockThreshold: 5,
    featured: false,
    active: true,
    tags: ["gifting", "keychain", "set", "souvenir"],
    weight: 45,
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "artisan-gift-hamper",
    name: "Artisan Gift Hamper",
    slug: "artisan-gift-hamper",
    price: 2199,
    category: "Gifting",
    collectionId: "gifting",
    description: "The ultimate Trendy Threadz gift: a curated hamper with a planter holder, one pair of earrings, a keychain set, and a handwritten note from the artisan who made it.",
    details: [
      "Includes: planter holder + lotus earrings + keychain set",
      "Hand-packed in a reusable jute basket",
      "Handwritten artisan card + brand story booklet",
      "Optional custom message at checkout",
      "Gift-ready — no extra wrapping needed",
    ],
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&h=600&q=80",
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&h=600&q=80",
    ],
    artisanId: "parvati-bai",
    stock: 7,
    lowStockThreshold: 5,
    featured: true,
    active: true,
    tags: ["gifting", "hamper", "bundle", "premium"],
    weight: 600,
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
];

export const seedSiteConfig: SiteConfig = {
  siteName: "Trendy Threadz",
  tagline: "Handcrafted by Women, Made with Love",
  heroTitle: "Handcrafted with Love, Empowered by Women",
  heroSubtitle: "Every stitch at Trendy Threadz supports rural Indian women artisans with sustainable income and global visibility for their craft.",
  announcementBar: "Free shipping on orders above ₹999 · Handmade with love from India 🌿",
  announcementBarEnabled: true,
  shippingFreeThreshold: 999,
  shippingFlatRate: 99,
  statsWomenEmpowered: 500,
  statsProductsSold: 5000,
  email: "hello@trendythreadz.in",
  phone: "+91 98765 43210",
  whatsapp: "+91 98765 43210",
  socialInstagram: "https://instagram.com/trendythreadz",
  socialFacebook: "https://facebook.com/trendythreadz",
  socialTwitter: "https://twitter.com/trendythreadz",
  socialYoutube: "",
  metaDescription: "Trendy Threadz — handcrafted crochet products made by rural Indian women artisans. Shop ethically made home decor, accessories, jewelry, and gifts.",
};

export function getProductById(id: string): Product | undefined {
  return seedProducts.find((p) => p.id === id);
}

export function getProductsByCollection(collectionId: string): Product[] {
  return seedProducts.filter((p) => p.collectionId === collectionId);
}

export function getCollectionBySlug(slug: string): Collection | undefined {
  return seedCollections.find((c) => c.slug === slug);
}

export function getArtisanById(id: string): Artisan | undefined {
  return seedArtisans.find((a) => a.id === id);
}

export function getProductsByArtisan(artisanId: string): Product[] {
  return seedProducts.filter((p) => p.artisanId === artisanId);
}

export function getFeaturedProducts(): Product[] {
  return seedProducts.filter((p) => p.featured);
}

export function getFeaturedArtisans(): Artisan[] {
  return seedArtisans.filter((a) => a.featured);
}
